(function(){
'use strict';
var CFG=window.BLACKOUT_CONFIG||{productName:'Blackout',website:'',watermarkEnabled:true};
var te=new TextEncoder(),td=new TextDecoder();
function join(){var a=[].slice.call(arguments),n=a.reduce(function(s,x){return s+x.length;},0),o=new Uint8Array(n),p=0;a.forEach(function(x){o.set(x,p);p+=x.length;});return o;}
function u32(n){var a=new Uint8Array(4);new DataView(a.buffer).setUint32(0,n);return a;}
function readU32(a,o){return new DataView(a.buffer,a.byteOffset+o,4).getUint32(0);}
function b64url(a){var s='',i;for(i=0;i<a.length;i++)s+=String.fromCharCode(a[i]);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function fromB64url(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';var b=atob(s),a=new Uint8Array(b.length);for(var i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a;}
function generateRecoveryKey(){var a=crypto.getRandomValues(new Uint8Array(32));return 'BO2-'+b64url(a);}
function isGeneratedKey(s){return /^BO2-[A-Za-z0-9_-]{43}$/.test(String(s||''));}
async function keyFor(keyText,salt){if(isGeneratedKey(keyText)){var raw=fromB64url(keyText.slice(4));return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']);}
  var material=await crypto.subtle.importKey('raw',te.encode(String(keyText)),'PBKDF2',false,['deriveKey']);
  return crypto.subtle.deriveKey({name:'PBKDF2',salt:salt,iterations:600000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);
}
async function encryptRecovery(originalBytes,keyText,meta){var raw=originalBytes instanceof Uint8Array?originalBytes:new Uint8Array(originalBytes);var salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));var header={magic:'BLACKOUT-R2',version:2,suite:'AES-256-GCM',kdf:isGeneratedKey(keyText)?'RAW-256':'PBKDF2-HMAC-SHA256-600000',salt:b64url(salt),iv:b64url(iv)};var headerBytes=te.encode(JSON.stringify(header));var metaBytes=te.encode(JSON.stringify(meta||{}));var plain=join(u32(metaBytes.length),metaBytes,raw);var key=await keyFor(keyText,salt);var cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:iv,additionalData:headerBytes,tagLength:128},key,plain));return join(te.encode('BOR2'),u32(headerBytes.length),headerBytes,cipher);}
async function decryptRecovery(envelope,keyText){var d=envelope instanceof Uint8Array?envelope:new Uint8Array(envelope);if(td.decode(d.slice(0,4))!=='BOR2')throw new Error('Not a Blackout R2 recovery payload');var hl=readU32(d,4),headerBytes=d.slice(8,8+hl),header=JSON.parse(td.decode(headerBytes));if(header.magic!=='BLACKOUT-R2'||header.version!==2)throw new Error('Unsupported recovery version');var salt=fromB64url(header.salt),iv=fromB64url(header.iv),key=await keyFor(keyText,salt);var plain=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:iv,additionalData:headerBytes,tagLength:128},key,d.slice(8+hl)));var ml=readU32(plain,0),meta=JSON.parse(td.decode(plain.slice(4,4+ml)));return{header:header,meta:meta,bytes:plain.slice(4+ml)};}
// PNG private ancillary chunk. Lower-case first byte marks it ancillary; second lower-case marks it private.
var crcTable=null;function crc32(bytes){if(!crcTable){crcTable=[];for(var n=0;n<256;n++){var c=n;for(var k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;crcTable[n]=c>>>0;}}var c=0xffffffff;for(var i=0;i<bytes.length;i++)c=crcTable[(c^bytes[i])&255]^(c>>>8);return(c^0xffffffff)>>>0;}
function makeChunk(type,data){var t=te.encode(type),body=join(t,data);return join(u32(data.length),body,u32(crc32(body)));}
function findPngChunk(bytes,type){if(bytes.length<12||td.decode(bytes.slice(1,4))!=='PNG')return null;var o=8;while(o+12<=bytes.length){var len=readU32(bytes,o),t=td.decode(bytes.slice(o+4,o+8));if(t===type)return bytes.slice(o+8,o+8+len);o+=12+len;}return null;}
function insertPngChunk(bytes,type,data){var o=8,parts=[bytes.slice(0,8)],inserted=false;while(o+12<=bytes.length){var len=readU32(bytes,o),t=td.decode(bytes.slice(o+4,o+8)),chunk=bytes.slice(o,o+12+len);if(t!==type){if(t==='IEND'&&!inserted){parts.push(makeChunk(type,data));inserted=true;}parts.push(chunk);}o+=12+len;}return join.apply(null,parts);}
async function putPngRecovery(blob,envelope){var bytes=new Uint8Array(await blob.arrayBuffer());return new Blob([insertPngChunk(bytes,'boR2',envelope)],{type:'image/png'});}
async function extractPngRecovery(blobOrBytes){var b=blobOrBytes instanceof Uint8Array?blobOrBytes:new Uint8Array(await blobOrBytes.arrayBuffer());return findPngChunk(b,'boR2');}
async function attachPdfRecovery(pdfBytes,envelope){var P=window.PDFLib;if(!P)throw new Error('pdf-lib is required');var doc=await P.PDFDocument.load(pdfBytes,{updateMetadata:false});var old=doc.catalog.get(P.PDFName.of('BlackoutRecovery'));if(old)doc.catalog.delete(P.PDFName.of('BlackoutRecovery'));var stream=doc.context.stream(envelope,{Type:'BlackoutRecovery',Version:2,Cipher:'AES256GCM'}),ref=doc.context.register(stream);doc.catalog.set(P.PDFName.of('BlackoutRecovery'),ref);return new Uint8Array(await doc.save({useObjectStreams:true,addDefaultPage:false,updateFieldAppearances:false}));}
async function extractPdfRecovery(pdfBytes){var P=window.PDFLib;if(!P)return null;try{var doc=await P.PDFDocument.load(pdfBytes,{updateMetadata:false});var ref=doc.catalog.get(P.PDFName.of('BlackoutRecovery'));if(!ref)return null;var raw=doc.context.lookup(ref);if(!raw)return null;if(raw.contents)return new Uint8Array(raw.contents);if(typeof raw.getContents==='function')return new Uint8Array(raw.getContents());return null;}catch(e){return null;}}
function brandLines(){return{top:'Redacted with '+(CFG.productName||'Blackout'),bottom:CFG.website||''};}
function applyCanvasWatermark(canvas){if(!CFG.watermarkEnabled)return canvas;var ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,scale=Math.max(.55,Math.min(2.2,Math.min(w,h)/900)),pad=Math.round(12*scale),barW=Math.round(24*scale),barH=Math.max(4,Math.round(7*scale)),font=Math.max(11,Math.round(14*scale)),small=Math.max(9,Math.round(11*scale)),lines=brandLines();ctx.save();ctx.font='600 '+font+'px Arial, sans-serif';var tw=ctx.measureText(lines.top).width,bw=lines.bottom?(function(){ctx.font='500 '+small+'px Arial, sans-serif';return ctx.measureText(lines.bottom).width;})():0;var boxW=Math.ceil(Math.max(barW+8*scale+tw,bw)+pad*2),boxH=Math.ceil((lines.bottom?font+small+9*scale:font+6*scale)+pad*2),x=w-boxW-Math.round(10*scale),y=h-boxH-Math.round(10*scale);ctx.fillStyle='rgba(255,255,255,.90)';ctx.fillRect(x,y,boxW,boxH);ctx.fillStyle='#000';ctx.fillRect(x+pad,y+pad+Math.round((font-barH)/2),barW,barH);ctx.font='600 '+font+'px Arial, sans-serif';ctx.textBaseline='top';ctx.fillText(lines.top,x+pad+barW+Math.round(8*scale),y+pad);if(lines.bottom){ctx.font='500 '+small+'px Arial, sans-serif';ctx.fillStyle='#555';ctx.fillText(lines.bottom,x+pad,y+pad+font+Math.round(5*scale));}ctx.restore();return canvas;}
async function applyPdfWatermark(doc){if(!CFG.watermarkEnabled)return doc;var P=window.PDFLib,regular=await doc.embedFont(P.StandardFonts.Helvetica),bold=await doc.embedFont(P.StandardFonts.HelveticaBold),lines=brandLines();doc.getPages().forEach(function(page){var size=page.getSize(),s=Math.max(.7,Math.min(1.15,Math.min(size.width,size.height)/612)),font=8*s,small=6.5*s,pad=5*s,barW=14*s,barH=4*s,topW=bold.widthOfTextAtSize(lines.top,font),bottomW=lines.bottom?regular.widthOfTextAtSize(lines.bottom,small):0,boxW=Math.max(barW+5*s+topW,bottomW)+pad*2,boxH=(lines.bottom?font+small+6*s:font+3*s)+pad*2,x=size.width-boxW-8*s,y=8*s;page.drawRectangle({x:x,y:y,width:boxW,height:boxH,color:P.rgb(1,1,1),opacity:.90});page.drawRectangle({x:x+pad,y:y+boxH-pad-font/2-barH/2,width:barW,height:barH,color:P.rgb(0,0,0)});page.drawText(lines.top,{x:x+pad+barW+5*s,y:y+boxH-pad-font,size:font,font:bold,color:P.rgb(0,0,0)});if(lines.bottom)page.drawText(lines.bottom,{x:x+pad,y:y+pad,size:small,font:regular,color:P.rgb(.28,.28,.28)});});return doc;}
// Local-only handoff between redaction and metadata pages.
function db(){return new Promise(function(resolve,reject){var r=indexedDB.open('blackout-local',1);r.onupgradeneeded=function(){if(!r.result.objectStoreNames.contains('handoff'))r.result.createObjectStore('handoff');};r.onsuccess=function(){resolve(r.result);};r.onerror=function(){reject(r.error);};});}
async function putHandoff(item){var d=await db();return new Promise(function(resolve,reject){var tx=d.transaction('handoff','readwrite');tx.objectStore('handoff').put(item,'current');tx.oncomplete=function(){d.close();resolve();};tx.onerror=function(){d.close();reject(tx.error);};});}
async function getHandoff(){var d=await db();return new Promise(function(resolve,reject){var tx=d.transaction('handoff','readonly'),r=tx.objectStore('handoff').get('current');r.onsuccess=function(){var v=r.result||null;tx.oncomplete=function(){d.close();resolve(v);};};r.onerror=function(){d.close();reject(r.error);};});}
async function clearHandoff(){var d=await db();return new Promise(function(resolve,reject){var tx=d.transaction('handoff','readwrite');tx.objectStore('handoff').delete('current');tx.oncomplete=function(){d.close();resolve();};tx.onerror=function(){d.close();reject(tx.error);};});}
window.BlackoutCore={config:CFG,generateRecoveryKey:generateRecoveryKey,isGeneratedKey:isGeneratedKey,encryptRecovery:encryptRecovery,decryptRecovery:decryptRecovery,putPngRecovery:putPngRecovery,extractPngRecovery:extractPngRecovery,attachPdfRecovery:attachPdfRecovery,extractPdfRecovery:extractPdfRecovery,applyCanvasWatermark:applyCanvasWatermark,applyPdfWatermark:applyPdfWatermark,putHandoff:putHandoff,getHandoff:getHandoff,clearHandoff:clearHandoff};
})();
